=begin
#The feedpushr API

#A simple feed aggregator daemon with sugar on top.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.2.2

=end

require 'spec_helper'
require 'json'

# Unit tests for FeedpushrClient::OutputApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'OutputApi' do
  before do
    # run before each test
    @api_instance = FeedpushrClient::OutputApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of OutputApi' do
    it 'should create an instance of OutputApi' do
      expect(@api_instance).to be_instance_of(FeedpushrClient::OutputApi)
    end
  end

  # unit tests for output_create
  # create output
  # Create a new output
  # @param payload 
  # @param [Hash] opts the optional parameters
  # @return [Output]
  describe 'output_create test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for output_delete
  # delete output
  # Delete an output
  # @param id Output ID
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'output_delete test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for output_get
  # get output
  # Retrieve output with given ID
  # @param id Output ID
  # @param [Hash] opts the optional parameters
  # @return [Output]
  describe 'output_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for output_list
  # list output
  # Retrieve all outputs definitions
  # @param [Hash] opts the optional parameters
  # @return [Array<Output>]
  describe 'output_list test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for output_specs
  # specs output
  # Retrieve all output types available
  # @param [Hash] opts the optional parameters
  # @return [Array<OutputSpec>]
  describe 'output_specs test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for output_update
  # update output
  # Update an output
  # @param id Output ID
  # @param payload 
  # @param [Hash] opts the optional parameters
  # @return [Output]
  describe 'output_update test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
