=begin
#The feedpushr API

#A simple feed aggregator daemon with sugar on top.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.2.2

=end

require 'spec_helper'
require 'json'

# Unit tests for FeedpushrClient::PshbApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'PshbApi' do
  before do
    # run before each test
    @api_instance = FeedpushrClient::PshbApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of PshbApi' do
    it 'should create an instance of PshbApi' do
      expect(@api_instance).to be_instance_of(FeedpushrClient::PshbApi)
    end
  end

  # unit tests for pshb_pub
  # pub pshb
  # Publication endpoint for PSHB hubs
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'pshb_pub test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for pshb_sub
  # sub pshb
  # Callback to validate the (un)subscription to the topic of a Hub
  # @param hub_challenge A hub-generated random string
  # @param hub_mode The literal string \&quot;subscribe\&quot; or \&quot;unsubscribe\&quot;
  # @param hub_topic The topic URL given in the corresponding subscription request
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :hub_lease_seconds The hub-determined number of seconds that the subscription will stay active before expiring
  # @return [nil]
  describe 'pshb_sub test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
